// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RainbowOF.Data.SQL;

namespace RainbowOF.Data.SQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("RainbowOF.Models.Items.ActiveItemAttribute", b =>
                {
                    b.Property<int>("ActiveItemAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsUsedForVariableType")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("ActiveItemAttributeId");

                    b.HasIndex("ActiveItemAttributeId", "ItemId")
                        .IsUnique();

                    b.ToTable("ActiveItemAttributes");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ActiveItemAttributeVariety", b =>
                {
                    b.Property<int>("ActiveItemAttributeVarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ItemAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemUoMId")
                        .HasColumnType("int");

                    b.Property<double>("UoMQtyPerItem")
                        .HasColumnType("float");

                    b.HasKey("ActiveItemAttributeVarietyId");

                    b.HasIndex("ItemUoMId");

                    b.HasIndex("ItemId", "ActiveItemAttributeVarietyId")
                        .IsUnique();

                    b.ToTable("ActiveItemAttributeVarieties");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemAbbreviatedName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ItemCategoryId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ItemCategoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacementItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemCategoryId1");

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.HasIndex("ParentItemId");

                    b.HasIndex("ReplacementItemId");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ItemAttribute", b =>
                {
                    b.Property<Guid>("ItemAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderBy")
                        .HasColumnType("int");

                    b.HasKey("ItemAttributeId");

                    b.HasIndex("AttributeName")
                        .IsUnique();

                    b.ToTable("ItemAttributes");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ItemAttributeVariety", b =>
                {
                    b.Property<Guid>("ItemAttributeVarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BGColour")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("FGColour")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid>("ItemAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("VarietyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemAttributeVarietyId");

                    b.HasIndex("VarietyName", "ItemAttributeId")
                        .IsUnique();

                    b.ToTable("ItemAttributeVarieties");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ItemCategory", b =>
                {
                    b.Property<Guid>("ItemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemCategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ItemCategoryId");

                    b.HasIndex("ItemCategoryName")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ItemUoM", b =>
                {
                    b.Property<int>("ItemUoMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BaseConversationFactor")
                        .HasColumnType("float");

                    b.Property<int?>("BaseUoMId")
                        .HasColumnType("int");

                    b.Property<int>("RoundTo")
                        .HasColumnType("int");

                    b.Property<string>("UoMName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UoMSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ItemUoMId");

                    b.HasIndex("BaseUoMId")
                        .IsUnique()
                        .HasFilter("[BaseUoMId] IS NOT NULL");

                    b.HasIndex("UoMName")
                        .IsUnique();

                    b.ToTable("ItemUoMs");
                });

            modelBuilder.Entity("RainbowOF.Models.Logs.WooSyncLog", b =>
                {
                    b.Property<int>("WooSyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("SectionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WooSyncDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("WooSyncLogId");

                    b.ToTable("WooSyncLogs");
                });

            modelBuilder.Entity("RainbowOF.Models.System.ClosureDate", b =>
                {
                    b.Property<int>("ClosureDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReopen")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NextPrepDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ClosureDateId");

                    b.HasIndex("EventName")
                        .IsUnique()
                        .HasFilter("[EventName] IS NOT NULL");

                    b.ToTable("ClosureDates");
                });

            modelBuilder.Entity("RainbowOF.Models.System.SysPrefs", b =>
                {
                    b.Property<int>("SysPrefsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DateLastPrepDateCalcd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultDeliveryPersonId")
                        .HasColumnType("int");

                    b.Property<bool>("DoReccuringOrders")
                        .HasColumnType("bit");

                    b.Property<int?>("GroupItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFolderPath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastReccurringDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReminderDaysNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("SysPrefsId");

                    b.ToTable("SysPrefs");
                });

            modelBuilder.Entity("RainbowOF.Models.System.WooSettings", b =>
                {
                    b.Property<int>("WooSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AreAttributesImported")
                        .HasColumnType("bit");

                    b.Property<bool>("AreCategoriesImported")
                        .HasColumnType("bit");

                    b.Property<bool>("AreItemQuantatiesImported")
                        .HasColumnType("bit");

                    b.Property<bool>("AreVarietiesMapped")
                        .HasColumnType("bit");

                    b.Property<string>("ConsumerKey")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ConsumerSecret")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsSecureURL")
                        .HasColumnType("bit");

                    b.Property<string>("JSONAPIPostFix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("OnlyInStockItemsImported")
                        .HasColumnType("bit");

                    b.Property<string>("QueryURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RootAPIPostFix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WooSettingsId");

                    b.ToTable("WooSettings");
                });

            modelBuilder.Entity("RainbowOF.Models.Woo.WooCategoryMap", b =>
                {
                    b.Property<int>("WooCategoryMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<Guid>("ItemCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WooCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("WooCategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("WooCategoryParentId")
                        .HasColumnType("int");

                    b.Property<string>("WooCategorySlug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("WooCategoryMapId");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("WooCategoryMaps");
                });

            modelBuilder.Entity("RainbowOF.Models.Woo.WooProductAttributeMap", b =>
                {
                    b.Property<Guid>("WooProductAttributeMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemAttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WooProductAttributeId")
                        .HasColumnType("int");

                    b.HasKey("WooProductAttributeMapId");

                    b.ToTable("WooProductAttributeMappings");
                });

            modelBuilder.Entity("RainbowOF.Models.Woo.WooProductAttributeTermMap", b =>
                {
                    b.Property<Guid>("WooProductAttributeTermMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemAttributeVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WooProductAttributeTermId")
                        .HasColumnType("int");

                    b.HasKey("WooProductAttributeTermMapId");

                    b.HasAlternateKey("ItemAttributeVarietyId", "WooProductAttributeTermId");

                    b.ToTable("WooProductAttributeTermMappings");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ActiveItemAttributeVariety", b =>
                {
                    b.HasOne("RainbowOF.Models.Items.ItemUoM", "ItemUoM")
                        .WithMany()
                        .HasForeignKey("ItemUoMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ItemUoM");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.Item", b =>
                {
                    b.HasOne("RainbowOF.Models.Items.ItemCategory", "ItemCategory")
                        .WithMany()
                        .HasForeignKey("ItemCategoryId1")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RainbowOF.Models.Items.Item", "ParentItem")
                        .WithMany()
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RainbowOF.Models.Items.Item", "ReplacementItem")
                        .WithMany()
                        .HasForeignKey("ReplacementItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ItemCategory");

                    b.Navigation("ParentItem");

                    b.Navigation("ReplacementItem");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ItemCategory", b =>
                {
                    b.HasOne("RainbowOF.Models.Items.ItemCategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("RainbowOF.Models.Items.ItemUoM", b =>
                {
                    b.HasOne("RainbowOF.Models.Items.ItemUoM", "BaseUoM")
                        .WithOne()
                        .HasForeignKey("RainbowOF.Models.Items.ItemUoM", "BaseUoMId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BaseUoM");
                });

            modelBuilder.Entity("RainbowOF.Models.Woo.WooCategoryMap", b =>
                {
                    b.HasOne("RainbowOF.Models.Items.ItemCategory", "ItemCategory")
                        .WithMany()
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
